name: Terraform CI

on:
  push:
    branches: ["main"]

jobs:
  terraform:
    name: Terraform Init | Validate | Plan
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # 3️⃣ Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 4️⃣ Terraform Init
      - name: Terraform Init
        working-directory: Book-main-infra/env/dev
        run: terraform init

      # 5️⃣ Terraform Validate
      - name: Terraform Validate
        working-directory: Book-main-infra/env/dev
        run: terraform validate

      # 6️⃣ Terraform Plan
      - name: Terraform Plan
        working-directory: Book-main-infra/env/dev
        run: terraform plan
# 6️⃣ Terraform Apply
      - name: Terraform Apply
        working-directory: Book-main-infra/env/dev
        run: terraform apply -auto-approve
